server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SERVER_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: eris-server

spring:
  application:
    name: eris-api-spring
  config:
    import: configserver:${CONFIG_SERVER_HOST}
  cloud:
    config:
      fail-fast: true
      tls:
        enabled: true
        key-store: classpath:keystore.p12
        key-store-password: ${SERVER_SSL_KEYSTORE_PASSWORD}
        key-password: ${SERVER_SSL_KEYSTORE_PASSWORD}
        key-store-type: PKCS12
        key-alias: eris-server
        trust-store: classpath:truststore.p12
        trust-store-password: ${SERVER_SSL_TRUSTSTORE_PASSWORD}
        trust-store-type: PKCS12
  datasource:
    url: jdbc:sqlite:./data/app.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  jpa:
    hibernate:ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB
      file-size-threshold: 0

security:
  jwt:
    expiration-time: 3600000
    refresh-token:
      expiration-time: 604800000
  cors.allowed-origins: https://localhost:4200

app:
  db-parser: sqlite
  messages:
    attachments-storage-path: 'C:/Users/Ban-K/Documents/dev/storage'

org:
  springframework:
    security:
      messaging:
        web:
          socket: DEBUG
    web:
      socket:
        server: DEBUG

logging:
  level:
    javax:
      net:
        ssl: DEBUG
    org:
      apache:
        http:
          wire: DEBUG
      springframework:
        security: DEBUG
